server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: enki
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderserver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
#        namespace: 0d9fb53d-e13e-4bca-b42a-68ac8d5fc39b
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

feign:
  client:
    config:
      orderservice:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
    #        Encoder: cn.itcast.user.config.FeignConfig
    httpclient:
      enabled: true # 开启feign对HttpClient的支持
      max-connections: 200 # 最大连接数
      max-connections-per-route: 200 # 每个路由的最大连接数